name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'my_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    example:
      +materialized: table
    staging:
      +materialized: view
    mart:
      +materialized: table

seeds:
  my_dbt_project:
    iris_dataset:
      +column_types:
        sepal_length: float
        sepal_width: float
        petal_length: float
        petal_width: float
        species: varchar